-- Migration: Add Unique Index on User Email and Remove ValueGeneratedNever from User Id
-- This migration adds the unique constraint to prevent duplicate users via email
-- And allows MySQL to auto-generate IDs for new users

USE NoWasteOfMoney;

-- Add unique index on Users.Email (prevents duplicate users)
CREATE UNIQUE INDEX IX_Users_Email ON Users (Email);

-- Note: The User.Id column will now be auto-generated by MySQL
-- This migration updates existing records to have proper GUID IDs
UPDATE Users 
SET Id = UUID() 
WHERE Id = '44444444-0000-0000-0000-000000000001';

-- Add unique index on Persons.Email (already exists, but ensuring it's there)
CREATE UNIQUE INDEX IF NOT EXISTS IX_Persons_Email ON Persons (Email);

SELECT 'Migration completed successfully!' AS Status;
